apiVersion: v2
name: accounts-service
description: accounts-service for Bank application
type: application
version: 1.0.0
appVersion: "2.0.0"
keywords:
  - bank
  - microservice
  - spring-boot
maintainers:
  - name: Bank App Team
