apiVersion: v2
name: postgresql
description: PostgreSQL database for Bank application
type: application
version: 1.0.0
appVersion: "14"
keywords:
  - postgresql
  - database
maintainers:
  - name: Bank App Team
