server:
  port: 9100

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb?currentSchema=auth
    username: ${DB_USERNAME:bank_user}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: auth

  jpa:
    hibernate:
      ddl-auto: update  # This will auto-create tables
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: auth

  flyway:
    enabled: true
    schemas: auth
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: mySecretKeyForBankingApplicationThatIsAtLeast256BitsLong
  access-token-validity: 3600
  refresh-token-validity: 604800

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    root: INFO
    com.bank.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  issuer: ${SECURITY_ISSUER:http://auth-server:9100}

management:
  endpoints:
    web:
      exposure:
        include: health,info

clients:
  gateway:
    service-id: ${GATEWAY_SERVICE_ID:bank-app-gateway-service}
  auth:
    service-id: ${AUTH_SERVICE_ID:bank-app-auth-server}
