server:
  port: 8084

spring:
  application:
    name: exchange-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank_user
    password: bank_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: exchange

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_ISSUER:http://bank-app-auth-server:9100}
      client:
        registration:
          exchange-service:
            client-id: exchange-service
            client-secret: exchange-secret
            authorization-grant-type: client_credentials
            scope: exchange.read
        provider:
          exchange-service:
            token-uri: ${TOKEN_URI:http://bank-app-auth-server:9100/oauth2/token}

security:
  internal-client:
    registration-id: exchange-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

