spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  cache:
    type: simple
  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb
    username: bank_user
    password: bank_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: exchange

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9100
      client:
        registration:
          exchange-service:
            client-id: exchange-service
            client-secret: exchange-secret
            authorization-grant-type: client_credentials
            scope: exchange.read
        provider:
          exchange-service:
            token-uri: http://auth-server:9100/oauth2/token

security:
  internal-client:
    registration-id: exchange-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

