spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb
    username: bank_user
    password: bank_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: cash

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9100
      client:
        registration:
          cash-service:
            client-id: cash-service
            client-secret: cash-secret
            authorization-grant-type: client_credentials
            scope: cash.write,cash.read,accounts.read,notifications.send
        provider:
          cash-service:
            token-uri: http://auth-server:9100/oauth2/token

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: cash-service

security:
  internal-client:
    registration-id: cash-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

clients:
  gateway:
    service-id: ${GATEWAY_SERVICE_ID:bank-app-gateway-service}
  auth:
    service-id: ${AUTH_SERVICE_ID:bank-app-auth-server}
