apiVersion: v2
name: bank-app-kibana
description: Kibana for log visualization in Bank Application
type: application
version: 1.0.0
appVersion: "8.5.1"

dependencies:
  - name: kibana
    version: "8.5.1"
    repository: https://helm.elastic.co
