apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
