{{- with .Values.config.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" $ }}-secret
  labels:
    {{- include "cash.labels" $ | nindent 4 }}
stringData:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
