apiVersion: v2
name: bank-app-grafana
description: Grafana dashboards and visualization for Bank Application
type: application
version: 1.0.0
appVersion: "11.3.0"

dependencies:
  - name: grafana
    version: "8.5.2"
    repository: https://grafana.github.io/helm-charts
