{{- if not .Values.kibana.secretMounts }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
type: Opaque
data:
  # Dummy certificate data (base64 encoded "dummy")
  ca.crt: ZHVtbXk=
{{- end }}
