kafka:
  enabled: true

  controller:
    replicaCount: 1
    persistence:
      enabled: true
      size: 4Gi
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m

  broker:
    replicaCount: 1
    persistence:
      enabled: true
      size: 4Gi
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m

  provisioning:
    enabled: true
    topics:
      - name: bank.notifications
        partitions: 1
        replicationFactor: 1
      - name: bank.notifications-retry
        partitions: 1
        replicationFactor: 1
      - name: bank.notifications-dlt
        partitions: 1
        replicationFactor: 1
      - name: bank.exchange.rates
        partitions: 1
        replicationFactor: 1
      - name: bank.exchange.rates-retry
        partitions: 1
        replicationFactor: 1
      - name: bank.exchange.rates-dlt
        partitions: 1
        replicationFactor: 1
