{{- with .Values.config.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-ui.fullname" $ }}-secret
  labels:
    {{- include "front-ui.labels" $ | nindent 4 }}
stringData:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
