{{- if and .Values.database.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange-generator.fullname" . }}-db
  labels:
    {{- include "exchange-generator.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
