{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifications.fullname" . }}-db
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
  {{- with .Values.database.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.database.service.port }}
      targetPort: postgres
  selector:
    app.kubernetes.io/name: {{ include "notifications.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
