apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications-service.fullname" . }}
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
