{{- with .Values.config.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" $ }}-config
  labels:
    {{- include "accounts.labels" $ | nindent 4 }}
data:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
