spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb
    username: bank_user
    password: bank_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: notifications

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dummy@example.com}
    password: ${MAIL_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9100
      client:
        registration:
          notifications-service:
            client-id: notifications-service
            client-secret: notifications-secret
            authorization-grant-type: client_credentials
            scope: notifications.send
        provider:
          notifications-service:
            token-uri: http://auth-server:9100/oauth2/token

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: notifications-service

security:
  internal-client:
    registration-id: notifications-service
management:
  endpoints:
    web:
      exposure:
        include: health,info

