{{- with .Values.config.initdbScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" $ }}-initdb
  labels:
    {{- include "postgres.labels" $ | nindent 4 }}
data:
{{- range $name, $content := . }}
  {{ $name }}: |-
    {{- $content | nindent 4 }}
{{- end }}
{{- end }}
