{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-auth
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
stringData:
  {{ .Values.auth.secretKeys.username }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.secretKeys.password }}: {{ .Values.auth.password | quote }}
  {{ .Values.auth.secretKeys.database }}: {{ .Values.auth.database | quote }}
{{- end }}
