apiVersion: v2
name: bank-app-elasticsearch
description: Elasticsearch for centralized logging in Bank Application
type: application
version: 1.0.0
appVersion: "8.5.1"

dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: https://helm.elastic.co
