apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.password | default "bank_password" | quote }}
  {{- if .Values.oauth2 }}
  OAUTH2_CLIENT_SECRET: {{ .Values.oauth2.clientSecret | default "change-me" | quote }}
  {{- end }}
  {{- if .Values.jwt }}
  JWT_SECRET: {{ .Values.jwt.secret | default "your-256-bit-secret-for-jwt-signing-change-in-production" | quote }}
  {{- end }}
