{{- if and .Values.global.discovery .Values.global.discovery.serviceAccount .Values.global.discovery.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.discovery.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-discovery-role" (include "bank-app.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-discovery-binding" (include "bank-app.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.discovery.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-discovery-role" (include "bank-app.fullname" .) }}
{{- end }}
