{{- if .Values.customKafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.customKafka.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kafka
    {{- include "bank-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: {{ .Values.customKafka.service.port }}
    targetPort: 9092
    protocol: TCP
    name: kafka
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: kafka-internal
  selector:
    app: kafka
{{- end }}
