{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    environment: {{ .Values.global.environment }}
    {{- include "bank-app.labels" . | nindent 4 }}
{{- end }}
